export const ACTION_TYPES = {
  /**
   * GET STAFF ACTION TYPES
   */
  ASSIGN_ADVISOR_START: 'ASSIGN_ADVISOR_START',
  ASSIGN_ADVISOR_SUCCESS: 'ASSIGN_ADVISOR_SUCCESS',
  ASSIGN_ADVISOR_FAILURE: 'ASSIGN_ADVISOR_FAILURE',

  ASSIGN_EXAMINER_START: 'ASSIGN_EXAMINER_START',
  ASSIGN_EXAMINER_SUCCESS: 'ASSIGN_EXAMINER_SUCCESS',
  ASSIGN_EXAMINER_FAILURE: 'ASSIGN_EXAMINER_FAILURE',

};
