export const ACTION_TYPES = {
  /**
   * GET STAFF ACTION TYPES
   */
  ASSIGN_GROUP_START: 'ASSIGN_GROUP_START',
  ASSIGN_GROUP_SUCCESS: 'ASSIGN_GROUP_SUCCESS',
  ASSIGN_GROUP_FAILURE: 'ASSIGN_GROUP_FAILURE',

  /**
   * LIST STAFF ACTION TYPES
   */

  LIST_GROUP_START: 'LIST_GROUP_START',
  LIST_GROUP_SUCCESS: 'LIST_GROUP_SUCCESS',
  LIST_GROUP_FAILURE: 'LIST_GROUP_FAILURE',

  /**
   * DELETE STAFF ACTION TYPES
   */

  DELETE_GROUP_START: 'DELETE_GROUP_START',
  DELETE_GROUP_SUCCESS: 'DELETE_GROUP_SUCCESS',
  DELETE_GROUP_FAILURE: 'DELETE_GROUP_FAILURE'
};
