export const ACTION_TYPES = {
  /**
   * GET STAFF ACTION TYPES
   */
  ADD_STAFF_START: 'ADD_STAFF_START',
  ADD_STAFF_SUCCESS: 'ADD_STAFF_SUCCESS',
  ADD_STAFF_FAILURE: 'ADD_STAFF_FAILURE',

  /**
   * LIST STAFF ACTION TYPES
   */

  LIST_STAFF_START: 'LIST_STAFF_START',
  LIST_STAFF_SUCCESS: 'LIST_STAFF_SUCCESS',
  LIST_STAFF_FAILURE: 'LIST_STAFF_FAILURE',

  /**
   * DELETE STAFF ACTION TYPES
   */

  DELETE_STAFF_START: 'DELETE_STAFF_START',
  DELETE_STAFF_SUCCESS: 'DELETE_STAFF_SUCCESS',
  DELETE_STAFF_FAILURE: 'DELETE_STAFF_FAILURE',

  //STUDENT

  ADD_STUDENT_START: 'ADD_STUDENT_START',
  ADD_STUDENT_SUCCESS: 'ADD_STUDENT_SUCCESS',
  ADD_STUDENT_FAILURE: 'ADD_STUDENT_FAILURE',

  //// delete students
  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  STUDENT_UPLOAD_START: 'STUDENT_UPLOAD_START',
  STUDENT_UPLOAD_SUCCESS: 'STUDENT_UPLOAD_SUCCESS',
  STUDENT_UPLOAD_FAILURE: 'STUDENT_UPLOAD_FAILURE',
  /**
   * LIST STUDENT ACTION TYPES
   */

  LIST_STUDENT_START: 'LIST_STUDENT_START',
  LIST_STUDENT_SUCCESS: 'LIST_STUDENT_SUCCESS',
  LIST_STUDENT_FAILURE: 'LIST_STUDENT_FAILURE',

  /**
   * DELETE STUDENT ACTION TYPES
   */

  DELETE_STUDENT_START: 'DELETE_STUDENT_START',
  DELETE_STUDENT_SUCCESS: 'DELETE_STUDENT_SUCCESS',
  DELETE_STUDENT_FAILURE: 'DELETE_STUDENT_FAILURE'
};
