export const STUDENTACTIONTYPE = {
    /*
    * Create Group
    */
    STUDENT_CREATE_GROUP_START: "STUDENT_CREATE_GROUP_START",
    STUDENT_CREATE_GROUP_SUCCESS: "STUDENT_CREATE_GROUP_SUCCESS",
    STUDENT_CREATE_GROUP_FAILURE: "STUDENT_CREATE_GROUP_FAILURE",
    
    /*
    * Fetch Group
    */
    STUDENT_FETCH_GROUP_START: "STUDENT_FETCH_GROUP_START",
    STUDENT_FETCH_GROUP_SUCCESS: "STUDENT_FETCH_GROUP_SUCCESS",
    STUDENT_FETCH_GROUP_FAILURE: "STUDENT_FETCH_GROUP_FAILURE",

    /**
     * Fetch Students
     */
    STUDENT_FETCH_START: "STUDENT_FETCH_START",
    STUDENT_FETCH_SUCCESS: "STUDENT_FETCH_SUCCESS",
    STUDENT_FETCH_FALIURE: "STUDENT_FETCH_FALIURE",
}