export const STUDENTACTIONTYPE = {
    /*
    * Create Group
    */
    STUDENT_CREATE_GROUP_START: "STUDENT_CREATE_GROUP_START",
    STUDENT_CREATE_GROUP_SUCCESS: "STUDENT_CREATE_GROUP_SUCCESS",
    STUDENT_CREATE_GROUP_FAILURE: "STUDENT_CREATE_GROUP_FAILURE",
    
    /*
    * Fetch Group
    */
    STUDENT_FETCH_GROUP_START: "STUDENT_FETCH_GROUP_START",
    STUDENT_FETCH_GROUP_SUCCESS: "STUDENT_FETCH_GROUP_SUCCESS",
    STUDENT_FETCH_GROUP_FAILURE: "STUDENT_FETCH_GROUP_FAILURE",

    /**
     * Fetch Students Who do not form group yet
     */
    STUDENT_FETCH_START: "STUDENT_FETCH_START",
    STUDENT_FETCH_SUCCESS: "STUDENT_FETCH_SUCCESS",
    STUDENT_FETCH_FALIURE: "STUDENT_FETCH_FALIURE",

    /**
     * Title Fetch
     */
    STUDENT_FETCH_TITLE_START: "STUDENT_FETCH_TITLE_START",
    STUDENT_FETCH_TITLE_SUCCESS: "STUDENT_FETCH_TITLE_SUCCESS",
    STUDENT_FETCH_TITLE_FAILURE: "STUDENT_FETCH_TITLE_FAILURE",
    /**
     *  Title Submission
     */
    STUDENT_TITLE_SUBMISSION_START: "STUDENT_TITLE_SUBMISSION_START",
    STUDENT_TITLE_SUBMISSION_SUCCESS: "STUDENT_TITLE_SUBMISSION_SUCCESS",
    STUDENT_TITLE_SUBMISSION_FAILURE: "STUDENT_TITLE_SUBMISSION_FAILURE",
    /**
         * Title Fetch
         */
    STUDENT_FETCH_PROPOSAL_DOCS_START: "STUDENT_FETCH_PROPOSAL_DOCS_START",
    STUDENT_FETCH_PROPOSAL_DOCS_SUCCESS: "STUDENT_FETCH_PROPOSAL_DOCS_SUCCESS",
    STUDENT_FETCH_PROPOSAL_DOCS_FAILURE: "STUDENT_FETCH_PROPOSAL_DOCS_FAILURE",
 
    /**
     * Proposal Docs Submission
     */
    STUDENT_PROPOSAL_DOCS_SUBMISSION_START: "STUDENT_PROPOSAL_DOCS_SUBMISSION_START",
    STUDENT_PROPOSAL_DOCS_SUBMISSION_SUCCESS: "STUDENT_PROPOSAL_DOCS_SUBMISSION_SUCCESS",
    STUDENT_PROPOSAL_DOCS_SUBMISSION_FAILURE: "STUDENT_PROPOSAL_DOCS_SUBMISSION_FAILURE",
    /**
     * Title Fetch
     */
    STUDENT_FETCH_SRS_DOCS_START: "STUDENT_FETCH_SRS_DOCS_START",
    STUDENT_FETCH_SRS_DOCS_SUCCESS: "STUDENT_FETCH_SRS_DOCS_SUCCESS",
    STUDENT_FETCH_SRS_DOCS_FAILURE: "STUDENT_FETCH_SRS_DOCS_FAILURE",

    /**
     *  SRS Docs Submission
     */
    STUDENT_SRS_DOCS_SUBMISSION_START: "STUDENT_SRS_DOCS_SUBMISSION_START",
    STUDENT_SRS_DOCS_SUBMISSION_SUCCESS: "STUDENT_SRS_DOCS_SUBMISSION_SUCCESS",
    STUDENT_SRS_DOCS_SUBMISSION_FAILURE: "STUDENT_SRS_DOCS_SUBMISSION_FAILURE",
    /**
         * Title Fetch
         */
    STUDENT_FETCH_SDS_DOCS_START: "STUDENT_FETCH_SDS_DOCS_START",
    STUDENT_FETCH_SDS_DOCS_SUCCESS: "STUDENT_FETCH_SDS_DOCS_SUCCESS",
    STUDENT_FETCH_SDS_DOCS_FAILURE: "STUDENT_FETCH_SDS_DOCS_FAILURE",

    /**
     *  SDS Docs Submission
     */
    STUDENT_SDS_DOCS_SUBMISSION_START: "STUDENT_SDS_DOCS_SUBMISSION_START",
    STUDENT_SDS_DOCS_SUBMISSION_SUCCESS: "STUDENT_SDS_DOCS_SUBMISSION_SUCCESS",
    STUDENT_SDS_DOCS_SUBMISSION_FAILURE: "STUDENT_SDS_DOCS_SUBMISSION_FAILURE",
    /**
         * Title Fetch
         */
    STUDENT_FETCH_SOURCE_CODE_START: "STUDENT_FETCH_SOURCE_CODE_START",
    STUDENT_FETCH_SOURCE_CODE_SUCCESS: "STUDENT_FETCH_SOURCE_CODE_SUCCESS",
    STUDENT_FETCH_SOURCE_CODE_FAILURE: "STUDENT_FETCH_SOURCE_CODE_FAILURE",

    /**
     *  SOURCE CODE Submission
     */
    STUDENT_SOURCE_CODE_SUBMISSION_START: "STUDENT_SOURCE_CODE_SUBMISSION_START",
    STUDENT_SOURCE_CODE_SUBMISSION_SUCCESS: "STUDENT_SOURCE_CODE_SUBMISSION_SUCCESS",
    STUDENT_SOURCE_CODE_SUBMISSION_FAILURE: "STUDENT_SOURCE_CODE_SUBMISSION_FAILURE",
 
 
}