export const ASSIGN_COORDINATOR_TYPES = {
  /**
   * GET STAFF ACTION TYPES
   */
  ASSIGN_COORDINATOR_START: 'ASSIGN_COORDINATOR_START',
  ASSIGN_COORDINATOR_SUCCESS: 'ASSIGN_COORDINATOR_SUCCESS',
  ASSIGN_COORDINATOR_FAILURE: 'ASSIGN_COORDINATOR_FAILURE',

  /**
   * LIST STAFF ACTION TYPES
   */

  LIST_COORDINATOR_START: 'LIST_COORDINATOR_START',
  LIST_COORDINATOR_SUCCESS: 'LIST_COORDINATOR_SUCCESS',
  LIST_COORDINATOR_FAILURE: 'LIST_COORDINATOR_FAILURE',

  /**
   * DELETE STAFF ACTION TYPES
   */

  DELETE_COORDINATOR_START: 'DELETE_COORDINATOR_START',
  DELETE_COORDINATOR_SUCCESS: 'DELETE_COORDINATOR_SUCCESS',
  DELETE_COORDINATOR_FAILURE: 'DELETE_COORDINATOR_FAILURE'
};
