export const ASSIGN_COORDINATOR_TYPES = {
    /**
     * GET STAFF ACTION TYPES
     */
    ASSIGN_COORDINATOR_START:"ASSIGN_COORDINATOR_START",
    ASSIGN_COORDINATOR_SUCCESS:"ASSIGN_COORDINATOR_SUCCESS",
    ASSIGN_COORDINATOR_FAILURE:"ASSIGN_COORDINATOR_FAILURE",
}
