// export const GET_STAFF_MEMBER = "GET_STAFF_MEMBER";
// export const CREATE_ITEM = "CREATE_ITEM";
// export const RETRIEVE_ITEMS = "RETRIEVE_ITEMS";
// export const UPDATE_ITEM = "UPDATE_ITEM";
// export const DELETE_ITEM = "DELETE_ITEM";
// export const DELETE_ALL_ITEMS = "DELETE_ALL_ITEMS";



export const ADMINACTIONTYPES = {


    /**
     * GET STAFF ACTION TYPES
     */

    STAFF_FETCH_START:"STAFF_FETCH_START",
    STAFF_FETCH_SUCCESS:"STAFF_FETCH_SUCCESS",
    STAFF_FETCH_FAILURE:"STAFF_FETCH_FAILURE",


    /**
     * UPDATE STAFF ACTION TYPES
     */

    STAFF_UPDATE_START:"STAFF_UPDATE_START",
    STAFF_UPDATE_SUCCESS:"STAFF_UPDATE_SUCCESS",
    STAFF_UPDATE_FAILURE:"STAFF_UPDATE_FAILURE",
   

    /**
     * DELETE STAFF ACTION TYPES
     */

    STAFF_DELETE_START:"STAFF_DELETE_START",
    STAFF_DELETE_SUCCESS:"STAFF_DELETE_SUCCESS",
    STAFF_DELETE_FAILURE:"STAFF_DELETE_FAILURE",


    /**
     * GET STUDENT ACTION TYPES
     */

    STUDENT_FETCH_START:"STUDENT_FETCH_START",
    STUDENT_FETCH_SUCCESS:"STUDENT_FETCH_SUCCESS",
    STUDENT_FETCH_FAILURE:"STUDENT_FETCH_FAILURE",


    /**
     * UPDATE STUDENT ACTION TYPES
     */

     STUDENT_UPDATE_START:"STUDENT_UPDATE_START",
     STUDENT_UPDATE_SUCCESS:"STUDENT_UPDATE_SUCCESS",
     STUDENT_UPDATE_FAILURE:"STUDENT_UPDATE_FAILURE",


    /**
     * DELETE STUDENT ACTION TYPES
     */

     STUDENT_DELETE_START:"STUDENT_DELETE_START",
     STUDENT_DELETE_SUCCESS:"STUDENT_DELETE_SUCCESS",
     STUDENT_DELETE_FAILURE:"STUDENT_DELETE_FAILURE",
}

