export const ADD_BATCH_TYPES = {
    /**
     * GET STAFF ACTION TYPES
     */
    ADD_BATCH_START: 'ADD_BATCH_START',
    ADD_BATCH_SUCCESS: 'ADD_BATCH_SUCCESS',
    ADD_BATCH_FAILURE: 'ADD_BATCH_FAILURE',
  };
  