export const ACTION_TYPES = {

  
    LIST_EXAMINER_GROUP_START: 'LIST_EXAMINER_GROUP_START',
    LIST_EXAMINER_GROUP_SUCCESS: 'LIST_EXAMINER_GROUP_SUCCESS',
    LIST_EXAMINER_GROUP_FAILURE: 'LIST_EXAMINER_GROUP_FAILURE',
  

  

  
  };
  