export const ACTION_TYPES = {
  /**
   * GET STAFF ACTION TYPES
   */
  ADD_DEADLINE_START: 'ADD_DEADLINE_START',
  ADD_DEADLINE_SUCCESS: 'ADD_DEADLINE_SUCCESS',
  ADD_DEADLINE_FAILURE: 'ADD_DEADLINE_FAILURE',

  /**
   * LIST STAFF ACTION TYPES
   */

  LIST_DEADLINE_START: 'LIST_DEADLINE_START',
  LIST_DEADLINE_SUCCESS: 'LIST_DEADLINE_SUCCESS',
  LIST_DEADLINE_FAILURE: 'LIST_DEADLINE_FAILURE',

  /**
   * STAFF ACTION TYPES
   */

  DELETE_DEADLINE_START: 'DELETE_DEADLINE_START',
  DELETE_DEADLINE_SUCCESS: 'DELETE_DEADLINE_SUCCESS',
  DELETE_DEADLINE_FAILURE: 'DELETE_DEADLINE_FAILURE',

  /**
   *LIST SUBMISSIONTYPE ACTION TYPES
   */

  LIST_SUBMSSIONTYPE_START: 'LIST_SUBMSSIONTYPE_START',
  LIST_SUBMSSIONTYPE_SUCCESS: 'LIST_SUBMSSIONTYPE_SUCCESS',
  LIST_SUBMSSIONTYPE_FAILURE: 'LIST_SUBMSSIONTYPE_FAILURE',

  ADD_SUBMSSIONTYPE_START: 'ADD_SUBMSSIONTYPE_START',
  ADD_SUBMSSIONTYPE_SUCCESS: 'ADD_SUBMSSIONTYPE_SUCCESS',
  ADD_SUBMSSIONTYPE_FAILURE: 'ADD_SUBMSSIONTYPE_FAILURE',








  ADD_SEMISTER_START: 'ADD_SEMISTER_START',
  ADD_SEMISTER_SUCCESS: 'ADD_SEMISTER_SUCCESS',
  ADD_SEMISTER_FAILURE: 'ADD_SEMISTER_FAILURE',


 LIST_SEMISTER_START: 'LIST_SEMISTER_START',
 LIST_SEMISTER_SUCCESS: 'LIST_SEMISTER_SUCCESS',
 LIST_SEMISTER_FAILURE: 'LIST_SEMISTER_FAILURE',


};
